### ISSUE TITLE
:question Getting "No desktop file." when I open my new desktops

### ISSUE THREAD

**Issue by nottoseethesun** [ryuslash/desktop-registry#1]
The old desktops work - the buffer list is loaded and things work normally.  As for the new ones, even if I use `desktop-save`, the buffers are never loaded.

I've tried `desktop-registry-auto-register` but that doesn't seem to help; the base functionality would be to just save all the buffers from a designated desktop such that they are loaded when that desktop is chosen.

While this was working for me for quite a while, for some reason it's not working for me now - any ideas?

**Comment by ryuslash** [comment]
Hi,

I have no idea why that should happen since I haven't changed anything in a while. Which version of Emacs are you using? And what are the exact steps you're taking to cause this problem?

`desktop-registry` doesn't handle the saving or loading of buffers itself, it uses Emacs' built-in `desktop` library for that. All `desktop-registry` does is remember where each desktop is located to make it easier to load them and switch to them.

I've just tried creating a new desktop file, which seems to work fine for me. 
1. I opened a file which isn't saved in any desktop yet.
2. I saved the desktop file with `desktop-save-in-desktop-dir`, which prompted me to specify the directory I want to use (since no desktop was loaded)
3. I cleared the desktop with `desktop-clear`, the file I opened is closed.
4. I loaded the desktop with `desktop-registry-change-desktop` and the file I opened shows up again. 

The only procedure from `desktop-registry` that is being used in this situation is `desktop-registry-change-desktop` and that is only a wrapper around `desktop-change-dir` providing completion from the desktop registry.

 I'm using a checkout of Emacs' master branch from about a week ago, though.

**Comment by nottoseethesun** [comment]
Thanks for the help!  Working for me now.  Your steps above helped me to clear this up.  I got this to work for me by doing `desktop-registry-add-directory` (`a` in the buffer pulled up by M-x `desktop-registry-list-desktops`), where I specified the top-level dir for the new desktop I wanted.  Then I proceeded to your Step #1, above.

**Comment by ryuslash** [comment]
Glad to hear you got it to work!
